#include "sorting_algorithms_project/include/quick_sort/quick_sort_iter.h"
#include "sorting_algorithms_project/include/select_sort/selection_sort.h"
#include "sorting_algorithms_project/include/merge_sort/merge_sort_iter.h"
#include "sorting_algorithms_project/include/insertion_sort/itertion_sort.h"
#include "sorting_algorithms_project/include/counting_sort/counting_sort.h"
#include "sorting_algorithms_project/include/bubble_sort/bubble_sort.h"
